In [1]:
import pandas as pd 
import geopandas as geo
import fiona

In [2]:
df = pd.read_csv(r'/Users/natalie_kraft/Documents/LAS/Pew2017_ITrain.csv')
shape = geo.read_file('/Users/natalie_kraft/Documents/LAS/countries.geojson')
df

,Unnamed: 0,ID,Country,desc_day,country_satis,nostalgia50,trust_gov,RESPONSE,econ_sit,improve_econ,...,d_adult_us,d_tenure5,d_tenure1,political_scale2,d_political_scale_us,d_homephone_us,d_working_cell,d_hhcell,d_numcell,d_density
0,0,19163.0,India,2.0,1.0,2.0,2.0,0.0,2.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.000000,1.666667,0.0
1,1,18311.0,India,3.0,0.0,2.0,2.0,0.0,3.0,0.0,...,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.666667,1.000000,0.0
2,2,18415.0,India,3.0,1.0,0.0,3.0,1.0,4.0,0.0,...,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.666667,1.000000,0.0
3,3,18128.0,India,1.0,0.0,0.0,2.0,0.0,2.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.666667,1.000000,0.0
4,4,18519.0,India,2.0,0.0,0.0,3.0,1.0,2.0,0.0,...,5.0,0.0,0.0,0.0,0.0,1.0,0.0,0.333333,1.000000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31460,625,13311.0,Greece,2.0,0.0,2.0,2.0,0.0,2.0,0.0,...,1.0,0.0,0.0,2.0,0.0,1.0,0.0,0.666667,1.000000,4.0
31461,626,12938.0,Greece,2.0,0.0,0.0,1.0,0.0,1.0,0.0,...,1.0,0.0,0.0,3.0,0.0,1.0,0.0,0.333333,1.000000,1.0
31462,627,13259.0,Greece,2.0,0.0,2.0,1.0,0.0,1.0,0.0,...,1.0,0.0,0.0,2.0,0.0,1.0,0.0,0.333333,1.000000,4.0
31463,628,13121.0,Greece,2.0,0.0,0.0,1.0,0.0,1.0,0.0,...,3.0,0.0,0.0,2.0,0.0,1.0,0.0,0.333333,1.000000,2.0
31464,629,13106.0,Greece,2.0,0.0,0.0,1.0,0.0,1.0,0.0,...,2.0,0.0,0.0,1.0,0.0,0.0,0.0,0.333333,1.000000,4.0

In [3]:
for i in range(0, len(df)):
    
    if df['Country'][i] == 'United States':
        df['Country'][i] = 'United States of America'
    
    if df['Country'][i] == 'Tanzania':
        df['Country'][i] = "United Republic of Tanzania"

<ipython-input-3-7037dc984b45>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Country'][i] = 'United States of America'
<ipython-input-3-7037dc984b45>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Country'][i] = "United Republic of Tanzania"

In [4]:
df.groupby('Country')['trust_gov'].sum() / df.groupby('Country')['trust_gov'].count()

Country
Argentina                      2.006545
Australia                      2.367072
Brazil                         1.660377
Canada                         2.787918
Chile                          1.871011
Colombia                       1.841545
France                         1.827446
Germany                        2.927711
Ghana                          3.122093
Greece                         1.507937
Hungary                        2.524496
India                          3.292800
Indonesia                      3.120924
Israel                         2.512010
Italy                          2.000000
Japan                          2.616511
Jordan                         2.445415
Kenya                          2.782456
Lebanon                        1.719544
Mexico                         1.794195
Netherlands                    2.943526
Nigeria                        2.606618
Peru                           1.847545
Philippines                    3.113941
Poland                         2.305006
Russia                         2.838535
Senegal                        2.811206
South Africa                   2.357798
South Korea                    2.026144
Spain                          1.877470
Sweden                         2.692412
Tunisia                        1.841333
Turkey                         0.000000
United Kingdom                 2.452292
United Republic of Tanzania    3.332090
United States of America       2.449956
Venezuela                      2.011968
Vietnam                        3.106160
Name: trust_gov, dtype: float64

In [5]:
df.head()

,Unnamed: 0,ID,Country,desc_day,country_satis,nostalgia50,trust_gov,RESPONSE,econ_sit,improve_econ,...,d_adult_us,d_tenure5,d_tenure1,political_scale2,d_political_scale_us,d_homephone_us,d_working_cell,d_hhcell,d_numcell,d_density
0,0,19163.0,India,2.0,1.0,2.0,2.0,0.0,2.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.000000,1.666667,0.0
1,1,18311.0,India,3.0,0.0,2.0,2.0,0.0,3.0,0.0,...,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.666667,1.000000,0.0
2,2,18415.0,India,3.0,1.0,0.0,3.0,1.0,4.0,0.0,...,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.666667,1.000000,0.0
3,3,18128.0,India,1.0,0.0,0.0,2.0,0.0,2.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.666667,1.000000,0.0
4,4,18519.0,India,2.0,0.0,0.0,3.0,1.0,2.0,0.0,...,5.0,0.0,0.0,0.0,0.0,1.0,0.0,0.333333,1.000000,0.0

In [6]:
shp = pd.DataFrame()
for i, col in enumerate(df.columns):
    if type(df[col][0]) != str:
        shp[col] = df.groupby('Country')[col].sum() / df.groupby('Country')[col].count()

In [7]:
shp['fav_US']

Country
Argentina                      3.244764
Australia                      3.146199
Brazil                         3.130728
Canada                         3.144816
Chile                          3.239805
Colombia                       3.187306
France                         3.098279
Germany                        3.055779
Ghana                          3.555039
Greece                         3.134392
Hungary                        3.113353
India                          3.411200
Indonesia                      3.110960
Israel                         3.311842
Italy                          3.130644
Japan                          3.103862
Jordan                         3.125473
Kenya                          3.456140
Lebanon                        3.397604
Mexico                         3.141161
Netherlands                    3.128099
Nigeria                        3.572304
Peru                           3.168820
Philippines                    3.343610
Poland                         3.144354
Russia                         3.186793
Senegal                        3.221681
South Africa                   3.435270
South Korea                    3.091939
Spain                          3.264822
Sweden                         3.139115
Tunisia                        3.465778
Turkey                         3.226941
United Kingdom                 3.237918
United Republic of Tanzania    3.368988
United States of America       3.611836
Venezuela                      3.302748
Vietnam                        3.370467
Name: fav_US, dtype: float64

In [8]:
shp = shp.drop(columns=['Unnamed: 0', 'ID'])
shp['year'] = "2017"

In [9]:
shp

,desc_day,country_satis,nostalgia50,trust_gov,RESPONSE,econ_sit,improve_econ,personal_econ,children_betteroff2,satisfied_democracy,...,d_tenure5,d_tenure1,political_scale2,d_political_scale_us,d_homephone_us,d_working_cell,d_hhcell,d_numcell,d_density,year
Country,,,,,,,,,,,,,,,,,,,,,
Argentina,2.412304,0.000000,0.792321,2.006545,0.252618,1.978185,0.000000,0.000000,2.030541,0.000000,...,0.000000,0.000000,2.777923,0.000000,0.547557,0.000000,0.918848,1.553229,0.000000,2017
Australia,2.311291,0.000000,1.204678,2.367072,0.502024,2.577148,0.000000,0.000000,1.542510,0.000000,...,0.000000,0.000000,3.049933,0.000000,0.629780,0.838057,0.654971,1.190283,2.533063,2017
Brazil,2.492363,0.136119,0.835130,1.660377,0.235849,1.772237,3.747978,2.534591,2.176550,0.000000,...,0.000000,0.000000,2.741240,0.000000,0.302785,0.000000,0.831986,1.321653,0.000000,2017
Canada,2.293059,0.000000,1.365039,2.787918,0.704370,2.595116,0.000000,0.000000,1.565553,0.000000,...,0.000000,0.000000,3.079263,0.000000,0.584404,0.806769,0.549700,1.184233,2.578835,2017
Chile,2.215869,0.000000,1.053191,1.871011,0.158245,2.289007,0.000000,0.000000,2.438830,0.000000,...,0.000000,0.000000,2.590426,0.000000,0.389628,0.000000,0.960550,1.412234,0.000000,2017
Colombia,2.574345,0.000000,0.684421,1.841545,0.126498,2.050599,0.000000,0.000000,1.695073,0.000000,...,0.000000,0.000000,2.713715,0.000000,0.379494,0.000000,0.967155,2.372836,0.000000,2017
France,2.195199,0.000000,0.878623,1.827446,0.217391,1.984601,0.000000,0.000000,1.361413,0.000000,...,0.000000,0.000000,3.053442,0.000000,0.722373,0.938406,0.836051,1.374547,1.737319,2017
Germany,2.157519,0.000000,1.552432,2.927711,0.726908,3.231147,0.000000,0.000000,1.882195,0.000000,...,0.000000,0.000000,2.833110,0.000000,0.793396,0.949576,0.792950,1.281124,2.341812,2017
Ghana,2.436822,0.000000,0.962791,3.122093,0.729070,2.301938,0.000000,0.000000,2.419380,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.025581,0.000000,0.872868,1.282171,0.000000,2017
Greece,2.134921,0.000000,0.729630,1.507937,0.119048,1.258730,0.000000,0.000000,1.500000,0.000000,...,0.000000,0.000000,2.788889,0.000000,0.800000,0.000000,0.523810,1.040741,2.841270,2017
Hungary,2.082133,0.000000,0.905860,2.524496,0.576369,2.319885,0.000000,0.000000,1.939001,0.000000,...,0.000000,0.000000,3.017291,0.000000,0.506244,0.000000,0.563881,1.107589,2.357349,2017
India,2.285689,0.691911,1.539200,3.292800,0.901333,3.166400,0.000000,0.000000,2.659022,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.122311,0.000000,0.848178,1.216178,0.000000,2017
Indonesia,2.266757,0.000000,1.379076,3.120924,0.838315,2.746830,0.000000,0.000000,2.414402,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.208786,0.000000,0.668025,1.205163,0.000000,2017
Israel,2.140750,0.000000,1.175306,2.512010,0.518331,2.648546,0.000000,0.000000,2.130215,0.000000,...,0.000000,0.000000,3.207754,0.000000,0.596713,0.000000,0.745891,1.075011,0.000000,2017
Italy,2.103746,0.000000,0.690682,2.000000,0.247839,1.840538,0.000000,0.000000,1.557637,0.000000,...,0.000000,0.000000,2.891451,0.000000,0.453890,0.000000,0.602305,1.132565,2.344380,2017
Japan,2.055925,0.000000,1.553484,2.616511,0.593875,2.436751,0.000000,0.000000,1.511318,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.782512,0.904572,0.602752,1.176209,2.428762,2017
Jordan,2.099563,0.000000,0.597089,2.445415,0.492576,1.913537,0.000000,0.000000,1.885590,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.064629,0.000000,0.881514,1.099272,0.000000,2017
Kenya,2.384016,0.000000,0.893177,2.782456,0.663158,2.185965,0.000000,0.000000,1.780507,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.035088,0.000000,0.806238,1.244055,0.000000,2017
Lebanon,2.126205,0.000000,0.777973,1.719544,0.144610,1.574642,0.000000,0.000000,1.733567,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.741455,0.000000,0.891323,1.062518,0.000000,2017
Mexico,2.301671,0.145998,0.447669,1.794195,0.180739,1.914248,0.000000,0.000000,1.662269,0.000000,...,0.000000,0.000000,2.469217,0.000000,0.313105,0.000000,0.828056,1.423043,0.000000,2017
Netherlands,2.273186,0.000000,1.533058,2.943526,0.767218,3.080349,0.000000,0.000000,1.808540,0.000000,...,0.000000,0.000000,3.240588,0.000000,0.638200,0.955005,0.730028,1.349862,1.930211,2017
Nigeria,2.637255,0.000000,0.851307,2.606618,0.544118,2.111111,0.000000,0.000000,2.464461,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.045343,0.000000,0.708742,1.247549,0.000000,2017
Peru,2.366494,0.000000,0.816968,1.847545,0.116279,2.460810,0.000000,0.000000,2.259690,0.000000,...,0.000000,0.000000,2.759259,0.000000,0.300603,0.000000,0.855297,1.231697,0.000000,2017
Philippines,2.474084,0.596962,1.239500,3.113941,0.801609,2.920018,0.000000,0.000000,2.400804,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.037534,0.000000,0.697051,1.270777,0.000000,2017
Poland,2.067520,0.000000,1.417540,2.305006,0.422584,2.629026,0.000000,0.000000,2.042685,0.000000,...,0.000000,0.000000,2.955374,0.000000,0.377183,0.000000,0.616608,1.094296,2.124563,2017
Russia,2.177748,0.621891,1.237449,2.838535,0.694708,2.444143,3.382180,2.533243,2.280868,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.336499,0.000000,0.635911,1.383537,0.000000,2017
Senegal,2.272432,0.000000,0.963053,2.811206,0.610231,2.814048,0.000000,0.000000,2.169306,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.100690,0.000000,0.898904,1.492489,0.000000,2017
South Africa,2.424737,0.000000,1.011213,2.357798,0.424057,2.180428,0.000000,0.000000,1.856269,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.142712,0.000000,0.827047,1.386001,0.000000,2017
South Korea,2.118954,0.000000,1.543355,2.026144,0.252288,1.851852,0.000000,0.000000,1.768627,0.000000,...,0.000000,0.000000,2.690196,0.000000,0.511111,0.000000,0.000000,1.032680,3.292810,2017
Spain,2.110233,0.000000,1.483970,1.877470,0.204216,2.074660,0.000000,0.000000,1.557751,0.000000,...,0.000000,0.000000,2.887132,0.000000,0.723759,0.974967,0.800176,1.233202,1.916557,2017
Sweden,2.326558,0.000000,1.414182,2.692412,0.670732,2.999548,0.000000,0.000000,1.902439,0.000000,...,0.000000,0.000000,3.191509,0.000000,0.485998,0.970190,0.929088,1.313460,2.168925,2017
Tunisia,2.189333,0.000000,0.732000,1.841333,0.296000,1.649333,0.000000,0.000000,1.978667,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.158667,0.000000,0.910667,1.172444,0.000000,2017
Turkey,2.126555,0.602317,1.437580,0.000000,0.000000,2.819391,0.000000,0.000000,2.305877,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.119262,0.000000,0.868297,1.070356,0.000000,2017
United Kingdom,2.259397,0.000000,1.190830,2.452292,0.511772,2.464271,0.000000,0.000000,1.505576,0.000000,...,0.000000,0.000000,3.031805,0.000000,0.708798,0.891367,0.752169,1.370095,2.104502,2017
United Republic of Tanzania,2.348673,0.000000,1.072139,3.332090,0.901741,2.526119,0.000000,0.000000,2.216833,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.034826,0.000000,0.657960,1.128109,0.000000,2017
United States of America,2.379170,0.000000,1.102408,2.449956,0.519582,2.621990,0.000000,0.000000,1.781549,0.000000,...,0.619089,0.718306,0.000000,2.046707,0.434001,0.973890,0.589788,1.270090,2.415434,2017
Venezuela,2.414450,0.142730,0.339982,2.011968,0.305851,1.677305,3.751330,2.163121,1.897606,0.000000,...,0.000000,0.000000,2.656028,0.000000,0.465869,0.000000,0.837323,1.584220,0.000000,2017
Vietnam,2.209699,0.000000,1.846658,3.106160,0.834862,3.110529,0.000000,0.000000,2.926606,3.074268,...,0.000000,0.000000,0.000000,0.000000,0.110092,0.000000,0.926606,1.154653,0.000000,2017

In [16]:
shp.to_csv("/Users/natalie_kraft/Documents/LAS/AggPewShp.csv")

In [10]:
export = pd.merge(shape, shp, left_on="ADMIN", right_on="Country", how="outer")

In [11]:
export[['ADMIN', 'geometry', 'fav_US', 'fav_Russia', 'fav_China']].to_file("/Users/natalie_kraft/Documents/LAS/AggPew.geojson", driver = "GeoJSON")

In [12]:
export

,ADMIN,ISO_A3,geometry,desc_day,country_satis,nostalgia50,trust_gov,RESPONSE,econ_sit,improve_econ,...,d_tenure5,d_tenure1,political_scale2,d_political_scale_us,d_homephone_us,d_working_cell,d_hhcell,d_numcell,d_density,year
0,Aruba,ABW,"POLYGON ((-69.99694 12.57758, -69.93639 12.531...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afghanistan,AFG,"POLYGON ((71.04980 38.40866, 71.05714 38.40903...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Angola,AGO,"MULTIPOLYGON (((11.73752 -16.69258, 11.73851 -...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Anguilla,AIA,"MULTIPOLYGON (((-63.03767 18.21296, -63.09952 ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Albania,ALB,"POLYGON ((19.74777 42.57890, 19.74601 42.57993...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
250,Samoa,WSM,"MULTIPOLYGON (((-171.57002 -13.93816, -171.564...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
251,Yemen,YEM,"MULTIPOLYGON (((53.30824 12.11839, 53.31027 12...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
252,South Africa,ZAF,"MULTIPOLYGON (((37.86378 -46.94085, 37.83644 -...",2.424737,0.0,1.011213,2.357798,0.424057,2.180428,0.0,...,0.0,0.0,0.0,0.0,0.142712,0.0,0.827047,1.386001,0.0,2017
253,Zambia,ZMB,"POLYGON ((31.11984 -8.61663, 31.14102 -8.60619...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
254,Zimbabwe,ZWE,"POLYGON ((30.01065 -15.64623, 30.05024 -15.640...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
export.to_csv("/Users/natalie_kraft/Documents/LAS/AggPewAll.csv")

In [ ]:
# test = geo.read_file("/Users/natalie_kraft/Documents/LAS/AggPew.geojson")